### PR TITLE
LPS-97871 Remove back-end logic to disable/enable Management Bar once it's no longer needed.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:test:sf

**Comment by natocesarrego** [comment]
ci:test:relevant

**Comment by phcp** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by phcp** [comment]
Just started reviewing :)

**Comment by phcp** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76515.

**Pull request closed without merging**
