### PR TITLE
LPS-104351 Update tests

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test:sf

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by phcp** [comment]
Just started reviewing :)

**Comment by phcp** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/274. [See changes here.](https://github.com/phcp/liferay-portal/compare/d6bb8b365d45~3...d6bb8b365d45)

**Pull request closed without merging**
