### PR TITLE
LPS-98518 | LPS-104037 Improve expected values on PerformanceByAssigneeCard test

### PR DESCRIPTION
**Pull request by gabrielpramos**

### CODE REVIEW

**Comment by gabrielpramos** [comment]
ci:test:sf

**Comment by gabrielpramos** [comment]
ci:test:relevant

**Comment by phcp** [comment]
Just started reviewing :)

**Comment by phcp** [comment]
Pull request submitted to https://github.com/inacionery/liferay-portal/pull/260. [See changes here.](https://github.com/phcp/liferay-portal/compare/ab442d0f9ca5~1...ab442d0f9ca5)

**Pull request closed without merging**
